easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Categorie
       - App\Entity\Emprunt
       - App\Entity\Media
       - App\Entity\Messages
       - App\Entity\Outils
       - App\Entity\Users
       - App\Entity\Villes
    # site_name:
    #    - '<img src="https://symfony.com/logos/symfony_white_01.png" />'
