easy_admin:
  entities:
    Categorie:
      class: App\Entity\Categorie
      form:
        fields:
          - {property: 'designation'}
          - {property: 'type'}
      templates:
        edit: categorie/edit.html.twig
  list:
    actions:
      - {name: 'show', icon: 'pencil', label: 'detail'}
      - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
      - {name: 'delete', icon: 'trash', label: false,css_class: 'btn btn-danger'}
